### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by Amaar-V** [Kekoa-Pickett/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [ ] All relevant URLs written as markdown links
  - Does not give markdown link to download VSCode
- [ ] All relevant code examples written with backticks (```)
  - Code is not written in backticks: `ls`
- [x] All screenshots correspond to the described steps
- [ ] All titles of sections are formatted as headers or similar
  - Missing headers for each section
- [x] Lab report is on its own page, not the index page
- [ ] Last example shows how to run remotely saving time
  - Does not show running remotely or how it saves time
- [x] Text is formatted in a way that was easy for the grader to read

Additional comments from your grader:
Remember that the report is supposed to be you showing how to each task and describe it with text, feel free to ask questions if you are unsure.
*Please leave a comment if you have any questions, thanks!*

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by Kekoa-Pickett** [comment]
I believe I fixed everything. I just didn't know exactly how to format or what to write.

**Comment by Amaar-V** [comment]
I see, thank you for the fixes, and well done!
